version: "3.7"
services:
  labs-test:
    image: node:latest
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules/
    container_name: labs-test
    ports:
      - "3000:3000"
    command: bash -c "npm install && npm run start"