version: "3.7"
services:
  labs-test:
    image: node:latest
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules/
    container_name: labs-test
    environment:
      - REACT_APP_KEY=<key>
      - PORT=80
    ports:
      - "80:80"
    command: bash -c "npm install && npm run build && npm run serve"
  